
export default new Map([
["src/content/docs/adr/adr-009-state-fraud-proofs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fadr%2Fadr-009-state-fraud-proofs.mdx&astroContentModuleFlag=true")],
["src/content/docs/adr/adr-010-exec-api.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fadr%2Fadr-010-exec-api.mdx&astroContentModuleFlag=true")],
["src/content/docs/adr/adr-011-remote-signer.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fadr%2Fadr-011-remote-signer.mdx&astroContentModuleFlag=true")],
["src/content/docs/adr/adr-012-based-sequencing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fadr%2Fadr-012-based-sequencing.mdx&astroContentModuleFlag=true")],
["src/content/docs/adr/adr-014-header-and-data-separation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fadr%2Fadr-014-header-and-data-separation.mdx&astroContentModuleFlag=true")],
["src/content/docs/adr/adr-017-node-pruning.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fadr%2Fadr-017-node-pruning.mdx&astroContentModuleFlag=true")],
["src/content/docs/adr/adr-020-validation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fadr%2Fadr-020-validation.mdx&astroContentModuleFlag=true")],
["src/content/docs/adr/adr-022-validator-network.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fadr%2Fadr-022-validator-network.mdx&astroContentModuleFlag=true")],
["src/content/docs/concepts/block-lifecycle.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fconcepts%2Fblock-lifecycle.mdx&astroContentModuleFlag=true")],
["src/content/docs/concepts/transaction-flow.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fconcepts%2Ftransaction-flow.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/advanced/forced-inclusion.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fadvanced%2Fforced-inclusion.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/celestia-gas-calculator.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fcelestia-gas-calculator.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/da/celestia-da.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fda%2Fcelestia-da.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/da/local-da.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fda%2Flocal-da.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/deploy/testnet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fdeploy%2Ftestnet.mdx&astroContentModuleFlag=true")],
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/learn/sequencing/single.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Flearn%2Fsequencing%2Fsingle.mdx&astroContentModuleFlag=true")],
["src/content/docs/learn/specs/block-manager.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Flearn%2Fspecs%2Fblock-manager.mdx&astroContentModuleFlag=true")],
["src/content/docs/learn/specs/template.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Flearn%2Fspecs%2Ftemplate.mdx&astroContentModuleFlag=true")],
["src/content/docs/learn/transaction-flow.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Flearn%2Ftransaction-flow.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/specs/block-manager.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fspecs%2Fblock-manager.mdx&astroContentModuleFlag=true")]]);
		